//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genel_Ulke_Raporu
    {
        public int ID { get; set; }
        public Nullable<int> ulkeID { get; set; }
        public string Yil { get; set; }
        public Nullable<int> Ithalat_ulkeID { get; set; }
        public Nullable<decimal> Ithalat { get; set; }
        public Nullable<int> Ihracat_ulkeID { get; set; }
        public Nullable<decimal> Ihracat { get; set; }
    
        public virtual UlkeListesi UlkeListesi { get; set; }
        public virtual UlkeListesi UlkeListesi1 { get; set; }
        public virtual UlkeListesi UlkeListesi2 { get; set; }
    }
}
