//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TradeMapDBEntities : DbContext
    {
        public TradeMapDBEntities()
            : base("name=TradeMapDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Genel_Ulke_Raporu> Genel_Ulke_Raporu { get; set; }
        public virtual DbSet<Ozel_Ulke_Raporu> Ozel_Ulke_Raporu { get; set; }
        public virtual DbSet<UlkeListesi> UlkeListesi { get; set; }
        public virtual DbSet<View_Base_GenelUlkeRapor> View_Base_GenelUlkeRapor { get; set; }
        public virtual DbSet<View_Base_OzelUlkeRapor> View_Base_OzelUlkeRapor { get; set; }
        public virtual DbSet<View_Base_Ulkeler> View_Base_Ulkeler { get; set; }
        public virtual DbSet<View_Presentation_GenelUlke> View_Presentation_GenelUlke { get; set; }
    
        public virtual ObjectResult<Proc_GenelUlkeRapor_Islem_Result> Proc_GenelUlkeRapor_Islem(string islem, string ulkeAd, string yil, string ithalat_ulkeAd, Nullable<int> ithalat, string ihracat_ulkeAd, Nullable<int> ihracat)
        {
            var islemParameter = islem != null ?
                new ObjectParameter("Islem", islem) :
                new ObjectParameter("Islem", typeof(string));
    
            var ulkeAdParameter = ulkeAd != null ?
                new ObjectParameter("ulkeAd", ulkeAd) :
                new ObjectParameter("ulkeAd", typeof(string));
    
            var yilParameter = yil != null ?
                new ObjectParameter("Yil", yil) :
                new ObjectParameter("Yil", typeof(string));
    
            var ithalat_ulkeAdParameter = ithalat_ulkeAd != null ?
                new ObjectParameter("Ithalat_ulkeAd", ithalat_ulkeAd) :
                new ObjectParameter("Ithalat_ulkeAd", typeof(string));
    
            var ithalatParameter = ithalat.HasValue ?
                new ObjectParameter("Ithalat", ithalat) :
                new ObjectParameter("Ithalat", typeof(int));
    
            var ihracat_ulkeAdParameter = ihracat_ulkeAd != null ?
                new ObjectParameter("Ihracat_ulkeAd", ihracat_ulkeAd) :
                new ObjectParameter("Ihracat_ulkeAd", typeof(string));
    
            var ihracatParameter = ihracat.HasValue ?
                new ObjectParameter("Ihracat", ihracat) :
                new ObjectParameter("Ihracat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GenelUlkeRapor_Islem_Result>("Proc_GenelUlkeRapor_Islem", islemParameter, ulkeAdParameter, yilParameter, ithalat_ulkeAdParameter, ithalatParameter, ihracat_ulkeAdParameter, ihracatParameter);
        }
    
        public virtual ObjectResult<Proc_OzelUlkeRapor_Islem_Result> Proc_OzelUlkeRapor_Islem(string islem, string ulkeAd, string yil, Nullable<int> ithalat, Nullable<int> ihracat, Nullable<int> hacim, Nullable<int> denge)
        {
            var islemParameter = islem != null ?
                new ObjectParameter("Islem", islem) :
                new ObjectParameter("Islem", typeof(string));
    
            var ulkeAdParameter = ulkeAd != null ?
                new ObjectParameter("ulkeAd", ulkeAd) :
                new ObjectParameter("ulkeAd", typeof(string));
    
            var yilParameter = yil != null ?
                new ObjectParameter("Yil", yil) :
                new ObjectParameter("Yil", typeof(string));
    
            var ithalatParameter = ithalat.HasValue ?
                new ObjectParameter("Ithalat", ithalat) :
                new ObjectParameter("Ithalat", typeof(int));
    
            var ihracatParameter = ihracat.HasValue ?
                new ObjectParameter("Ihracat", ihracat) :
                new ObjectParameter("Ihracat", typeof(int));
    
            var hacimParameter = hacim.HasValue ?
                new ObjectParameter("Hacim", hacim) :
                new ObjectParameter("Hacim", typeof(int));
    
            var dengeParameter = denge.HasValue ?
                new ObjectParameter("Denge", denge) :
                new ObjectParameter("Denge", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_OzelUlkeRapor_Islem_Result>("Proc_OzelUlkeRapor_Islem", islemParameter, ulkeAdParameter, yilParameter, ithalatParameter, ihracatParameter, hacimParameter, dengeParameter);
        }
    }
}
