//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UlkeListesi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UlkeListesi()
        {
            this.Genel_Ulke_Raporu = new HashSet<Genel_Ulke_Raporu>();
            this.Genel_Ulke_Raporu1 = new HashSet<Genel_Ulke_Raporu>();
            this.Genel_Ulke_Raporu2 = new HashSet<Genel_Ulke_Raporu>();
            this.Ozel_Ulke_Raporu = new HashSet<Ozel_Ulke_Raporu>();
        }
    
        public int ID { get; set; }
        public string ulkeAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genel_Ulke_Raporu> Genel_Ulke_Raporu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genel_Ulke_Raporu> Genel_Ulke_Raporu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genel_Ulke_Raporu> Genel_Ulke_Raporu2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ozel_Ulke_Raporu> Ozel_Ulke_Raporu { get; set; }
    }
}
